branch-defaults:
  default:
    deploy:
      artifact: ./www/Archive.zip
    environment: udagrampeniel-dev
    group_suffix: null
environment-defaults:
  udagrampeniel-dev:
    branch: null
    repository: null
global:
  application_name: udagrampeniel
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
