branch-defaults:
  default:
    environment: udacity-project2-nigel
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-starter-code
  branch: null
  default_ec2_keyname: udagram-nigel-dev
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
