branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: udagrammike-dev
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
