apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: $AWS_BUCKET
  AWS_PROFILE: $AWS_BUCKET
  AWS_REGION: $AWS_REGION
  JWT_SECRET: $JWT_SECRET
  POSTGRESS_DB: $POSTGRESS_DB
  POSTGRESS_HOST: $POSTGRESS_HOST
  URL: http://localhost:8100  
metadata:
  name: env-config
  